const elevatorTypes = {
  ADD_FLOOR_TO_ELEVATOR_QUE: "elevator/ADD_FLOOR_TO_ELEVATOR_QUE",
  PASS_FLOOR_TO_ELEVATOR: "elevator/PASS_FLOOR_TO_ELEVATOR",
  CHANGE_ELEVATOR_CURRENT_FLOOR: "elevator/CHANGE_ELEVATOR_CURRENT_FLOOR",
  CHANGE_ELEVATOR_BUSY_STATUS: "elevator/CHANGE_ELEVATOR_BUSY_STATUS",
  GET_STATE_FROM_STORAGE: "elevator/GET_STATE_FROM_STORAGE",
  INCREMENT_SETTING_PROP: "elevator/INCREMENT_SETTING_PROP",
  DECREMENT_SETTING_PROP: "elevator/DECREMENT_SETTING_PROP",
  RESET_ALL_ELEVATORS: "elevator/RESET_ALL_ELEVATORS",
};

export default elevatorTypes;
